apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    creationTimestamp: "2023-02-13T15:29:48Z"
    generation: 1
    name: default
    namespace: argocd
    resourceVersion: "6362301"
    uid: 6d8c41e2-b7ce-45fd-bf67-23fff44ec99b
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: '*'
      server: '*'
    sourceRepos:
    - '*'
  status: {}
kind: List
metadata:
  resourceVersion: ""