apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boto3-ip-finder
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-Chart
    repoURL: https://github.com/VirtualL/workshop_ci_cd
    targetRevision: HEAD